#pragma once
#include "Arduino.h"

enum ODriveControlMode {
    CONTROL_MODE_VOLTAGE_CONTROL             = 0,
    CONTROL_MODE_TORQUE_CONTROL              = 1,
    CONTROL_MODE_VELOCITY_CONTROL            = 2,
    CONTROL_MODE_POSITION_CONTROL            = 3,
};

enum ODriveInputMode {
    INPUT_MODE_INACTIVE                      = 0,
    INPUT_MODE_PASSTHROUGH                   = 1,
    INPUT_MODE_VEL_RAMP                      = 2,
    INPUT_MODE_POS_FILTER                    = 3,
    INPUT_MODE_MIX_CHANNELS                  = 4,
    INPUT_MODE_TRAP_TRAJ                     = 5,
    INPUT_MODE_TORQUE_RAMP                   = 6,
    INPUT_MODE_MIRROR                        = 7,
    INPUT_MODE_TUNING                        = 8,
};

enum ODriveAxisState {
    AXIS_STATE_UNDEFINED                     = 0,
    AXIS_STATE_IDLE                          = 1,
    AXIS_STATE_STARTUP_SEQUENCE              = 2,
    AXIS_STATE_FULL_CALIBRATION_SEQUENCE     = 3,
    AXIS_STATE_MOTOR_CALIBRATION             = 4,
    AXIS_STATE_ENCODER_INDEX_SEARCH          = 6,
    AXIS_STATE_ENCODER_OFFSET_CALIBRATION    = 7,
    AXIS_STATE_CLOSED_LOOP_CONTROL           = 8,
    AXIS_STATE_LOCKIN_SPIN                   = 9,
    AXIS_STATE_ENCODER_DIR_FIND              = 10,
    AXIS_STATE_HOMING                        = 11,
    AXIS_STATE_ENCODER_HALL_POLARITY_CALIBRATION = 12,
    AXIS_STATE_ENCODER_HALL_PHASE_CALIBRATION = 13,
    AXIS_STATE_ANTICOGGING_CALIBRATION       = 14,
    AXIS_STATE_HARMONIC_CALIBRATION          = 15,
    AXIS_STATE_HARMONIC_CALIBRATION_COMMUTATION = 16,
};



enum ODriveError {
    ODRIVE_ERROR_NONE                        = 0x00000000,
    ODRIVE_ERROR_INITIALIZING                = 0x00000001,
    ODRIVE_ERROR_SYSTEM_LEVEL                = 0x00000002,
    ODRIVE_ERROR_TIMING_ERROR                = 0x00000004,
    ODRIVE_ERROR_MISSING_ESTIMATE            = 0x00000008,
    ODRIVE_ERROR_BAD_CONFIG                  = 0x00000010,
    ODRIVE_ERROR_DRV_FAULT                   = 0x00000020,
    ODRIVE_ERROR_MISSING_INPUT               = 0x00000040,
    ODRIVE_ERROR_DC_BUS_OVER_VOLTAGE         = 0x00000100,
    ODRIVE_ERROR_DC_BUS_UNDER_VOLTAGE        = 0x00000200,
    ODRIVE_ERROR_DC_BUS_OVER_CURRENT         = 0x00000400,
    ODRIVE_ERROR_DC_BUS_OVER_REGEN_CURRENT   = 0x00000800,
    ODRIVE_ERROR_CURRENT_LIMIT_VIOLATION     = 0x00001000,
    ODRIVE_ERROR_MOTOR_OVER_TEMP             = 0x00002000,
    ODRIVE_ERROR_INVERTER_OVER_TEMP          = 0x00004000,
    ODRIVE_ERROR_VELOCITY_LIMIT_VIOLATION    = 0x00008000,
    ODRIVE_ERROR_POSITION_LIMIT_VIOLATION    = 0x00010000,
    ODRIVE_ERROR_WATCHDOG_TIMER_EXPIRED      = 0x01000000,
    ODRIVE_ERROR_ESTOP_REQUESTED             = 0x02000000,
    ODRIVE_ERROR_SPINOUT_DETECTED            = 0x04000000,
    ODRIVE_ERROR_BRAKE_RESISTOR_DISARMED     = 0x08000000,
    ODRIVE_ERROR_THERMISTOR_DISCONNECTED     = 0x10000000,
    ODRIVE_ERROR_CALIBRATION_ERROR           = 0x40000000,
};
